# Generated by Django 5.1.7 on 2025-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_right_answer_ordinance_question_ordinance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinance',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
