# fly.toml app configuration file generated for whatsup-crimson-water-2982 on 2025-03-22T16:41:05-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsup-crimson-water-2982'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"